### ISSUE TITLE
Hello~ So if I want to catch Arduino that send data.Can i use this project?

### ISSUE THREAD

**Issue by unitydragon** [giomurru/ble-framework#2]

**Comment by giomurru** [comment]
It depends. You can catch data transmitted with a BLE Mini. In theory it should work with any bluetooth low energy module attached to Arduino, but I never tested.

**Comment by lorandnagy** [comment]
Hi there,

Many thanks first of all for this project. I am working with a HM-10 ble module. I tried to connect to it, but I have failed yet. Any help would be appretiated. I can find the module, but I needed in default I can not read anything, because the gatt service address is not the correct one. So I changed it in the source plugin (RBLGattAttributes.java)

CLIENT_CHARACTERISTIC_CONFIG = 0000ffe0-0000-1000-8000-00805f9b34fb
BLE_SHIELD_TX=0000ffe1-0000-1000-8000-00805f9b34fb
BLE_SHIELD_RX=0000ffe1-0000-1000-8000-00805f9b34fb
BLE_SHIELD_SERVICE=0000ffe0-0000-1000-8000-00805f9b34fb
Did any of You try this?

Thank You,
Lorand
