### ISSUE TITLE
Stuck with the InitBLEFramework message, even with the sample

### ISSUE THREAD

**Issue by Tenes** [giomurru/ble-framework#3]
I'm trying to build a unity app that uses your framework but i can't get it to work, even the sample project doesn't work. I use an Android 7.0 version. 
Thanks in advance

**Comment by giomurru** [comment]
I'm working on the problem on the branch android-fix-dev. I switched to Android Studio build, so please ignore the instructions about ant. Furthermore Unity project already include the compiled jar android plugin and is ready to use. Unfortunately not everything is working.
You are welcome to contribute in the Android Plugin Project if you have any fix.

**Comment by Ume0344** [comment]
hey I'm not getting how to start, i have my unity App completed but dont know how to connect it with arduino.
Please help.

**Comment by giomurru** [comment]
Are you working on branch android-fix-dev?

**Comment by Ume0344** [comment]
No I am working on Arduino Uno which is connected to my sensors. I build the unity App on Android. All i want is to send the data from arduino to unity app via HC-05 bluetooth module.

**Comment by giomurru** [comment]
You can try to build the sample project in branch android-fix-dev with Android set as target. The build will generate a test application. Try to understand the code that interfaces with the plugin and modify it for your purpose. 
However I think the plugin needs some modification since you are not using a BLE device from RedBearLab. You probably have to modify the code here:
https://github.com/giomurru/ble-framework/blob/android-fix-dev/AndroidPluginProject/bleframework/src/main/java/com/gmurru/bleframework/RBLGattAttributes.java
with the ids for your BLE device.
I am talking about the variables
BLE_SHIELD_TX, BLE_SHIELD_RX, CLIENT_CHARACTERISTIC_CONFIG, BLE_SHIELD_SERVICE
I think you have to change them in order to make it work with your bluetooth module, but I don't know the values.

**Comment by Ume0344** [comment]
I also have this asset from unity https://www.assetstore.unity3d.com/en/#!/content/16467
I dont know how to use it. If you can help me.

**Comment by Ume0344** [comment]
Sorry for not mentioning it earlier.

**Comment by giomurru** [comment]
I am sorry Ume0344 for deleting your comment but it does not make sense for you to post a link to a commercial plugin. I don't mean to be rude but, since you paid for that, you should ask them for support.
