### ISSUE TITLE
No device found on iPhone 6s with iOS 11

### ISSUE THREAD

**Issue by kk17** [giomurru/ble-framework#4]
Below is the debug log from xcode:
```
2017-11-15 17:40:25.507969+0800 bleframework[5308:518616] scanForPeripheralsWithServices
2017-11-15 17:40:27.508815+0800 bleframework[5308:518616] Stopped Scanning
2017-11-15 17:40:27.508880+0800 bleframework[5308:518616] Known peripherals : 0
2017-11-15 17:40:27.509323+0800 bleframework[5308:518616] List of currently known peripherals :
2017-11-15 17:40:27.509351+0800 bleframework[5308:518616] No peripherals found
AppControllerBehavior: HandleOnBleDidCompletePeripheralScanErrorEvent: Error scanning for BLE peripherals: Fail: No device found
BLEFramework.Unity.BLEControllerEventHandler:OnBleDidCompletePeripheralScan(String)
```

**Comment by architek1** [comment]
I am having this same issue. Did you figure it out @kk17?

**Comment by kk17** [comment]
No，I use another plugin instead.

**Comment by nviverosb** [comment]
@architek1 what about you? could you make it work?

**Comment by kirax999** [comment]
Like what's really bad it looked very promising

**Comment by emdepdev** [comment]
@giomurru Done

**Comment by giomurru** [comment]
I think I know what is your problem. Are you sure that the RBL_SERVICE_UUID defined in BLEDefines.h is the same of your board? Please verify that you have one of these boards.
- BLE Shield
- BLE Mini
- Blend Micro
- Blend
- BLE Nano
- RBL nRF51822

I have BLE Mini and I tested the code on master in iOS 9 and iOS 11 and it works.
The code you want to change would cause the framework to find multiple devices different from the specific RedBearLab boards for which the framework was created (including duplicate UUIDs). Apple documentation clearly states that you should avoid this behavior to improve battery efficiency.
Read paragraphs `Minimize Processing of Duplicate Device Discoveries` and paragraph `Only Discover Services and Characteristics You Need` in the documentation https://developer.apple.com/library/content/documentation/Performance/Conceptual/EnergyGuide-iOS/BluetoothBestPractices.html.

If you want to support another board different from RedBearLab boards I suggest to change the values defined in the BLEDefines.h with those of your board and then try to adapt the code. I can not guarantee that this will work because this framework is intended for the specific boards in the list above. 

I am closing the issue.
