### ISSUE TITLE
Unable to run copyPlugin

### ISSUE THREAD

**Issue by timrbarrett** [giomurru/ble-framework#9]
Importing to latest version of Android Studio doesn't permit Run of copyPlugin.
"You can open this project using Android Studio, then click on Run 'copyPlugin' to generate and copy the plugin in the BleFramework/Assets/Plugin/Android folder."

Is there a way to manually perform the task?

**Comment by giomurru** [comment]
Are you sure there is no copyPlugin?
You have to go in Gradle Scripts -> build.gradle (Module: AndroidPlugin.bleframework)
Then scroll down the file and there is a green play button near the task copyPlugin. Click on it and it should work.
You can then find the generated plugin inside the folder BleFramework/Assets/Plugins/Android
Please let me know if this solves your problem.

![Screen Shot 2021-03-07 at 6 30 06 PM](https://user-images.githubusercontent.com/2816576/110248818-3d385280-7f73-11eb-80b7-9bf923c33aa5.png)

**Comment by timrbarrett** [comment]
I replied to the email that Github sent me - expecting it to appear here too, my apologies.

![image](https://user-images.githubusercontent.com/4627863/111065457-c4c11c80-84b1-11eb-9c33-69c9a9a9fac1.png)

I'm grateful to you : directing me to the exact file and how to execute the right mechanism. 
Unfortunately, when I do that I see a message Task 'copyPlugin' not found in root project 'ble-framework-master'.

(I downloaded a zip file and extracted the contents - instead of trusting to github desktop.) 

FYI: in your screenshot i see app, ble framework and gradlescript as the highest in your folders, mine looks quite different

**Comment by giomurru** [comment]
I think you probably opened the root folder while you should have opened the AndroidPlugin folder.
Follow these steps to fix.
1) Close the project you have opened.
2) Delete the ble-framework-master folder and extract the zip file again.
3) Now open Android Studio and choose "Open an existing project"
4) Select the folder AndroidPlugin inside the ble-framework-master and click Open
5) Ignore the error Invalid VCS root mapping. It's an error about git because you downloaded the repo using the zip file...
6) Now you should see a screen like the one I posted in the previous answer. Double click on build.gradle (Module: AndroidPlugin.bleframework) to open it.
7) Now click on the green play button on the left of task copyPlugin and choose the first run option.
![Screen Shot 2021-03-14 at 6 56 47 PM](https://user-images.githubusercontent.com/2816576/111078722-3a031080-84f7-11eb-851d-a7aeed1414f8.png)

**Comment by timrbarrett** [comment]
plugin generated! 

Thank-you for your patience in stepping through the process for me.

Tim

**Comment by timrbarrett** [comment]
That worked!

thank you.

**Comment by giomurru** [comment]
You're welcome :-)
